#######
# SITE SETTINGS
#
# title appears in the header
title: REDCap at Griffith
# title-icon appears in the header to give some pizazz (leave blank for none)
# choose from Font Awesome 5 free, https://fontawesome.com/icons?d=gallery&m=free
# some options: fas fa-wrench; fas fa-cogs; fas fa-code; fas fa-chalkboard-teacher; fas fa-book-open
title-icon: fas fa-pied-piper-hat
# description, keywords, and image for meta tags
description: "A companion resource to Griffith Library's Research Data Capture workshop"
keywords: "workshops, research, data, surveys, longitudinal, redcap"
featured-image: "/images/redcap-logo-full.png"
# add search box to footer? true/false
search: true

# author settings for cc-by, appears in the footer and credits
author: Yuri Banens
# your github username for link [optional]
github_username: GriffithUniLibrary
# year or date published
pub_year: 2021
# location of code, the full url to your github repository
source-code: https://github.com/GriffithUniLibrary/redcap

##########
# URL VARIABLES [optional!]
#
# Optional if using GitHub Pages! If building manually, these must be set correctly.
#
# use url for the domain, e.g. https://evanwill.github.io
# on gh-pages follow the pattern: https://username.github.io
url:
# use baseurl to add subsection of the domain, e.g. /workshop-template-b
# on gh-pages this is a / followed by the name of the repository
# baseurl is your github repository's name prefixed with a /
baseurl:


##########
# GOOGLE ANALYTICS [optional!]
#
# leave this blank or comment out to NOT include google code
# Add your google-analytics-id to automatically add the embed code, e.g. "UA-76328753-1"
google-analytics-id: UA-139142134-4

##########
# ROBOTS EXCLUDE [optional!]
#
# set noindex to true if you do NOT want Google to index your site
# noindex: true 


#######
# BUILD SETTINGS [usually leave as is]
#
# Defaults to simplify front matter
defaults:
  - scope:
      path: "content"
    values:
      layout: "section"
# Build settings
markdown: kramdown
